//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jcw.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jcw.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap AddHorizontalLine {
            get {
                object obj = ResourceManager.GetObject("AddHorizontalLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add horizontal marker to chart.
        /// </summary>
        public static string AddHorizontalMarkerToChartMenuText {
            get {
                return ResourceManager.GetString("AddHorizontalMarkerToChartMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap AddNote {
            get {
                object obj = ResourceManager.GetObject("AddNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note to chart.
        /// </summary>
        public static string AddNoteToChartMenuText {
            get {
                return ResourceManager.GetString("AddNoteToChartMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap AddVerticalLine {
            get {
                object obj = ResourceManager.GetObject("AddVerticalLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vertical marker to chart.
        /// </summary>
        public static string AddVerticalMarkerToChartMenuText {
            get {
                return ResourceManager.GetString("AddVerticalMarkerToChartMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BackButton {
            get {
                object obj = ResourceManager.GetObject("BackButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackMenuButtonText {
            get {
                return ResourceManager.GetString("BackMenuButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Border {
            get {
                object obj = ResourceManager.GetObject("Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ChartNote {
            get {
                object obj = ResourceManager.GetObject("ChartNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CircleMarker {
            get {
                object obj = ResourceManager.GetObject("CircleMarker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle markers visible.
        /// </summary>
        public static string CircleMarkersVisibleMenuText {
            get {
                return ResourceManager.GetString("CircleMarkersVisibleMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CloseHot {
            get {
                object obj = ResourceManager.GetObject("CloseHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ClosePressed {
            get {
                object obj = ResourceManager.GetObject("ClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string DefaultSaveChartAsImageName {
            get {
                return ResourceManager.GetString("DefaultSaveChartAsImageName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ForwardButton {
            get {
                object obj = ResourceManager.GetObject("ForwardButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal markers visible.
        /// </summary>
        public static string HorizontalMarkersVisibleMenuText {
            get {
                return ResourceManager.GetString("HorizontalMarkersVisibleMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Jcw {
            get {
                object obj = ResourceManager.GetObject("Jcw", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LineChartButtonText {
            get {
                return ResourceManager.GetString("LineChartButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MaximizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MaximizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MaximizeHot {
            get {
                object obj = ResourceManager.GetObject("MaximizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MaximizePressed {
            get {
                object obj = ResourceManager.GetObject("MaximizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart User Data.
        /// </summary>
        public static string MetadataBarText {
            get {
                return ResourceManager.GetString("MetadataBarText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MinimizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MinimizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MinimizeHot {
            get {
                object obj = ResourceManager.GetObject("MinimizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MinimizePressed {
            get {
                object obj = ResourceManager.GetObject("MinimizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text for chart note.
        /// </summary>
        public static string MissingChartNoteText {
            get {
                return ResourceManager.GetString("MissingChartNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart notes visible.
        /// </summary>
        public static string NotesVisibleMenuText {
            get {
                return ResourceManager.GetString("NotesVisibleMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Restore {
            get {
                object obj = ResourceManager.GetObject("Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("RestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RestoreHot {
            get {
                object obj = ResourceManager.GetObject("RestoreHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap RestorePressed {
            get {
                object obj = ResourceManager.GetObject("RestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPeg Image|*.jpg|Bitmap Image|*.bmp|Gif Image|*.gif|Png Image|*.png.
        /// </summary>
        public static string SaveChartAsImageDialogFilter {
            get {
                return ResourceManager.GetString("SaveChartAsImageDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Chart as Image File.
        /// </summary>
        public static string SaveChartAsImageDialogTitle {
            get {
                return ResourceManager.GetString("SaveChartAsImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart as image.
        /// </summary>
        public static string SaveChartAsImageMenuText {
            get {
                return ResourceManager.GetString("SaveChartAsImageMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Chart User Data.
        /// </summary>
        public static string SaveChartUserDataButtonText {
            get {
                return ResourceManager.GetString("SaveChartUserDataButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap SaveRequired {
            get {
                object obj = ResourceManager.GetObject("SaveRequired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        public static string ScatterChartButtonText {
            get {
                return ResourceManager.GetString("ScatterChartButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap SquareMarker {
            get {
                object obj = ResourceManager.GetObject("SquareMarker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Statistics.
        /// </summary>
        public static string StatisticsBarText {
            get {
                return ResourceManager.GetString("StatisticsBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical markers visible.
        /// </summary>
        public static string VerticalMarkersVisbleMenuText {
            get {
                return ResourceManager.GetString("VerticalMarkersVisbleMenuText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomInButtonText {
            get {
                return ResourceManager.GetString("ZoomInButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ZoomInSelected {
            get {
                object obj = ResourceManager.GetObject("ZoomInSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOutButtonText {
            get {
                return ResourceManager.GetString("ZoomOutButtonText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ZoomOutSelected {
            get {
                object obj = ResourceManager.GetObject("ZoomOutSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZoomReset {
            get {
                object obj = ResourceManager.GetObject("ZoomReset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Reset.
        /// </summary>
        public static string ZoomResetButtonText {
            get {
                return ResourceManager.GetString("ZoomResetButtonText", resourceCulture);
            }
        }
    }
}
